---
- name: Fix Neutron Configuration
  hosts: controller
  remote_user: heat-admin
  gather_facts: no
  become: true
  tasks:

  - name: Update Router Quota
    lineinfile:
      dest: /etc/neutron/neutron.conf
      insertafter: '^#quota_router'
      line: 'quota_router = 1'

  - name: Update Floating IP Qouta
    lineinfile:
      dest: /etc/neutron/neutron.conf
      insertafter: "^#quota_floatingip"
      line: 'quota_floatingip = 2'

  - name: Restart Neutron Server
    service:
      name: neutron-server
      state: restarted
