---
- name: Fixing the Search Domains
  hosts: all
  remote_user: heat-admin
  gather_facts: no
  become: true
  tasks:

  - name: Update the Search Domains
    lineinfile:
      dest: /etc/resolv.conf
      insertafter: "^search"
      line: 'search somethingelse.domain.com'
