---
- name: RPM GPG Key
  hosts: localhost
  connection: local
  tasks:
  - name: Check for Public Keys
    command: rpm -q gpg-pubkey
    register: rpm_gpg_pubkey
    
  - name: Run when gpg key doesn't exist
    shell: echo "{{ rpm_gpg_pubkey.stdout }}" > test
    when: rpm_gpg_pubkey.stdout == ""
