---
- name: RPM GPG Key
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Check for Public Keys
    local_action: command: rpm -q gpg-pubkey
    register: rpm_gpg_pubkey
  - debug: msg="{{ rpm_gpg_pubkey }}"
