---
- name: Update Openstack Configuration
  hosts: all
  remote_user: heat-admin
  gather_facts: no
  become: true

- include: keystone.yaml
- include: neutron_controller.yaml
- include: neutron_compute.yaml
- include: nova_compute.yaml
- include: nova_controller.yaml
